/* eslint-disable @next/next/no-img-element */
import { groq } from 'next-sanity';
import Head from 'next/head';
import Link from 'next/link';
import CardPost from '../components/CardPost';
import Header from '../components/Header';
import { sanityClient, urlFor } from '../sanity';
import { PostI } from '../typing';

interface Props {
  posts: [PostI];
}

const Home = ({ posts }: Props) => {
  console.log(posts);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <div className="bg-yellow-400 px-10 border-y border-black">
        <div className="flex py-6 max-w-5xl mx-auto  justify-between items-center">
          <div className="space-y-5 text-center md:text-left">
            <h1 className="text-3xl md:text-4xl lg:text-6xl max-w-xl font-bold">
              <span className="underline decoration-black decoration-4">
                Medium{' '}
              </span>
              is a place to write, read, and connect
            </h1>
            <h2 className="text-black text-sm md:text-base lg:text-lg">
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Culpa
              accusamus odio illo quaerat.
            </h2>
          </div>

          <img
            className="hidden md:inline-flex h-32 lg:h-full"
            src="/medium-m.png"
            alt="m logo"
          />
        </div>
      </div>
      {/* post */}
      <div className="max-w-5xl mx-auto">
        <div className="grid grid-cols-1 sm:grid-cols-2 mt-8 py-4 gap-4 md:grid-cols-3 lg:grid-cols-4">
          {posts?.map(post => (
            <CardPost key={post._id} post={post} />
          ))}
        </div>
      </div>
    </div>
  );
};

export default Home;

export const getServerSideProps = async () => {
  const query = groq`*[_type=='post']{
  _id,
  title,
  slug,
  body,
  mainImage,
  _createdAt,
  author ->{
  name,
  }
}
`;
  const posts = await sanityClient.fetch(query);

  return {
    props: {
      posts,
    },
  };
};
